<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Aplikasi Pemilihan Ketua OSIS</title>
    <link href="{{asset('css/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-image: url("{{asset('storage/bg-pliketos.png')}}");
            background-position: top;
            background-repeat: no-repeat;
        }

        .form-signin {
            width: 100%;
            max-width: 500px;
            padding: 15px;
            margin: auto;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
            margin-bottom: 15px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

        #loading {
            position: fixed;
            display: flex;
            text-align: center;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            opacity: 0.7;
            background-color: #000;
            z-index: 99;
        }

        .loading-image {
            z-index: 100;
            margin: auto;
        }
    </style>
  </head>
  <body class="text-center">
    <form class="form-signin">
        <a href="/">
            <img class="mb-4" src="{{ asset('storage/panitia_osis_logo.png') }}" alt="" height="72">
        </a>
        <h4 class="mb-3 font-weight-normal">PEMILIHAN KETUA OSIS <br> SMP NEGERI 23 BANJARMASIN</h4>
        <label for="nisn" class="sr-only">NISN</label>
        <input type="text" id="nisn" class="form-control" placeholder="NISN" required autofocus>
        <label for="code" class="sr-only">CODE</label>
        <input type="text" id="code" class="form-control" placeholder="CODE" required>
        <button class="btn btn-lg btn-danger btn-block" type="submit">KIRIM</button>
        <p class="mt-3 mb-3 text-muted">
            Made by Riyan Maulana, S.Kom for SMPN 23 Banjarmasin
        </p>
    </form>
    <div id="loading">
        <div>
            <svg class="loading-image" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-linecap="round" fill="none" stroke-dasharray="50.26548245743669 50.26548245743669" stroke="#ff0011" stroke-width="8" r="32" cy="50" cx="50">
                <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform"></animateTransform>
            </circle>
            <circle stroke-linecap="round" fill="none" stroke-dashoffset="36.12831551628262" stroke-dasharray="36.12831551628262 36.12831551628262" stroke="#ffffff" stroke-width="8" r="23" cy="50" cx="50">
                <animateTransform values="0 50 50;-360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform"></animateTransform>
            </circle><g></g></g><!-- [ldio] generated by https://loading.io -->
            </svg>
            <h3>SEDANG DIPROSES MOHON MENUNGGU...</h3>
        </div>
    </div>
    <script type="text/javascript" src="{{asset('js/jquery-3.7.1.min.js')}}"></script>
    <script>
        $(function(){
            $('#loading').hide();
            $('form').on('submit',function(e){
                e.preventDefault();
                $('#loading').show();

                setTimeout(() => {
                    window.location = 'proses/'+$('#nisn').val()+'/'+$('#code').val();
                }, 1000);
            })
        })
    </script>
  </body>
</html>
